
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame implements ActionListener{
    Timer tm;
    int x,y,velX=5,velY=5;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        //maximize JFrame
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Diskos = new javax.swing.JPanel();
        Bala = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Diskos.setBackground(new java.awt.Color(0, 0, 0));
        Diskos.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout DiskosLayout = new javax.swing.GroupLayout(Diskos);
        Diskos.setLayout(DiskosLayout);
        DiskosLayout.setHorizontalGroup(
            DiskosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        DiskosLayout.setVerticalGroup(
            DiskosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        Bala.setBackground(new java.awt.Color(255, 0, 51));
        Bala.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout BalaLayout = new javax.swing.GroupLayout(Bala);
        Bala.setLayout(BalaLayout);
        BalaLayout.setHorizontalGroup(
            BalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        BalaLayout.setVerticalGroup(
            BalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Diskos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Bala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(Bala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Diskos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int enter=0;
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        switch(key)
        {
            case KeyEvent.VK_RIGHT:
                if (Diskos.getLocation().x+10>=getContentPane().getWidth()-Diskos.getWidth()){
                    Diskos.setLocation(Diskos.getLocation().x,Diskos.getLocation().y);
                    if (enter==0){
                        Bala.setLocation(Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2,Bala.getLocation().y);
                        x=Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2;
                        y=Bala.getLocation().y;
                    }
                }
                else{
                    Diskos.setLocation(Diskos.getLocation().x+10,Diskos.getLocation().y);
                    if (enter==0){
                        Bala.setLocation(Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2,Bala.getLocation().y);
                        x=Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2;
                        y=Bala.getLocation().y;
                    }
                }
            break;
            case KeyEvent.VK_LEFT:
                if (Diskos.getLocation().x-10<=0){
                    Diskos.setLocation(Diskos.getLocation().x,Diskos.getLocation().y);
                    if (enter==0){
                        Bala.setLocation(Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2,Bala.getLocation().y);
                        x=Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2;
                        y=Bala.getLocation().y;
                    }
                }
                else{
                    Diskos.setLocation(Diskos.getLocation().x-10,Diskos.getLocation().y);
                    if (enter==0){
                        Bala.setLocation(Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2,Bala.getLocation().y);
                        x=Diskos.getLocation().x+Diskos.getWidth()/2-Bala.getWidth()/2;
                        y=Bala.getLocation().y;
                    }
                }
            break;
            case KeyEvent.VK_ENTER:
                if (enter==0){
                    enter=1;
                    tm = new Timer(5,this);
                    tm.start();
                }
                //setResizable(false);
            break;   
        }
    }//GEN-LAST:event_formKeyPressed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (enter==0){
            Diskos.setLocation(getContentPane().getWidth()/2-Diskos.getWidth()/2,  getContentPane().getHeight()-2*Diskos.getHeight());
            Bala.setLocation(getContentPane().getWidth()/2-Bala.getWidth()/2,  getContentPane().getHeight()-2*Bala.getHeight());
        }
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bala;
    private javax.swing.JPanel Diskos;
    // End of variables declaration//GEN-END:variables
@Override
    public void actionPerformed(ActionEvent e) {
        x=x+velX;
        y=y-velY;
        
        if (x+velX+Bala.getWidth()==getContentPane().getWidth()){ 
            System.out.println("nai");
            x=x+velX;
            Bala.setLocation(-x,y);
        }
        if (y+velY+Bala.getHeight()==getContentPane().getHeight()){
            System.out.println("nai nai");
            y=y-velY;
            Bala.setLocation(x,-y);
        }
        /*if (Bala.getX()+Bala.getWidth()==getContentPane().getWidth()|| Bala.getX()==0)
        Bala.setLocation(-x,y);
        if (Bala.getY()+Bala.getHeight()==getContentPane().getHeight()|| Bala.getY()==0)
        Bala.setLocation(x,-y);
        else*/
        Bala.setLocation(x,y);
    }
}
